### ISSUE TITLE
where is the jar?

### ISSUE THREAD

**Issue by yajun818** [michael-rapp/AndroidBottomSheet#10]
sorry, I am studing Android ，but I can't find the jar file,thx!

**Comment by michael-rapp** [comment]
There is no Jar. In Android dependencies are usually not packaged as Jars, because they do not only contain code (class files), but also resources such as images, XML files etc. Instead of manually adding dependencies as files, in Android development dependency management should be automated by using Gradle.

If you are using Android Studio (which I highly recommend), any project you create will contain a Gradle config by default. By declaring dependencies in the `build.gradle` file, libraries will automatically be added to your project. In case of this library you have to add the following to said file:

```xml
dependencies {
    compile 'com.github.michael-rapp:android-bottom-sheet:1.4.3'
}
```

**Comment by yajun818** [comment]
Got it,thank you.This Project is perfect!

**Comment by yajun818** [comment]
But,  there is a new problem when I use your project  as Library. 
 When I import the package“import de.mrapp.android.bottomsheet.R”，the  Android Studio hints that can't find R .Look forward to your favourable reply

**Comment by michael-rapp** [comment]
But you can import the other classes of the library? I can't imagine a reason why you should use the library's R class anyway. Each dependency and your project itself has a own R class. But you should always use the one from your app's package.
