### ISSUE TITLE
how to change item title size?

### ISSUE THREAD

**Issue by BigSnake1989** [michael-rapp/AndroidBottomSheet#7]
Hi Dear:
    My item title's Language is Chinese,Device's size is 1280*720,But it can not be fully displayed.My BottomSheet style is BottomSheet.Style.GRID.

**Comment by michael-rapp** [comment]
Hello,

The library uses the text size, which is recommended by Google's Material Design guidelines. It is not supposed to be changed. If your title is too long, you should think about using a shorter title first.

Nevertheless, you can set any custom view to be used as a `BottomSheet`'s title by using its `setCustomTitle`-method. Create a layout resource with the `TextView` you want to use, e.g. in the file `res/layout/custom_title.xml`. The id of the `TextView` must be `@android:id/title`. In the following you can see the `TextView`, which is used to display the title by default. Just modify it to fit your needs and add the attribute "android:textSize" (e.g. `android:textSize="10sp"`) to specify any text size.

``` xml
<TextView
    android:id="@android:id/title"
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="@dimen/bottom_sheet_title_height"
    android:drawablePadding="@dimen/bottom_sheet_drawable_padding"
    android:ellipsize="marquee"
    android:fadingEdge="horizontal"
    android:gravity="center_vertical"
    android:singleLine="true"
    android:textAppearance="?android:attr/textAppearanceMedium />
```

Then use the following code in order to use the specified `TextView` as the `BottomSheet`'s title:

``` java
BottomSheet.Builder builder = new BottomSheet.Builder(context);
// customize builder...
builder.setCustomTitle(R.layout.custom_title);
BottomSheet bottomSheet = builder.create();
```

**Comment by BigSnake1989** [comment]
It only change the sheet title size,but don't change the item title size.
if i won't to change the item title size,What should I do?

**Comment by BigSnake1989** [comment]
i change the system setting font size.

**Comment by michael-rapp** [comment]
I don't know exactly what you want to achive. There is no built-in option to change the font size of each grid item. However, it uses the text appearence `?android:attr/textAppearanceSmall`, maybe you can change this attribute in your `res\values\styles.xml` file.
